# 将 <xxx> 替换为你的实际配置
app:
  port: 8088
  serverHint: "<your conf>"
  salt: "<your conf>"
  maxUserActive: 3
  nodeID: 1
  globalUploadSize: "32mb"
  notifyEmail: "<your conf>"
  serverTimezone: "<your conf>"
  staticDir: "<your conf>"
dataSource:
  db:
    bizDB:
      dbType: sqlite
      dsn: "<your conf>"
      mark: "<your conf>"
    extraDB:
      dbType: sqlite
      dsn: "<your conf>"
      mark: "<your conf>"
cloudflare:
  accountID: "<your conf>"
  apiKey: "<your conf>"
  email: "<your conf>"
email:
  port: 587
  host: "<your conf>"
  password: "<your conf>"
  username: "<your conf>"
s3:
  accessKeyID: "<your conf>"
  accessKeySecret: "<your conf>"
  accountID: "<your conf>"
  bucketName: "<your conf>"
  endPoint: "<your conf[optional]>"
  linkedDomain: "<your conf[optional]>"
  token: "<your conf[optional]>"
oauth2Conf:
  github:
    endPoint: github
    clientId: "<your conf>"
    clientSecret: "<your conf>"
    redirectUrl: "<your conf>"
    scopes: ["<your conf>"]
  google:
    endPoint: google
    clientId: "<your conf>"
    clientSecret: "<your conf>"
    redirectUrl: "<your conf>"
    scopes: ["<your conf>"]
jwtConf:
  salt: "<your conf>"
  expired: "15d"
