# 将 <xxx> 替换为你的实际配置
app:
  port: 8088
  serverHint: "<your conf>"
  salt: "<your conf>"
  maxUserActive: 3
  nodeID: 1
dataSource:
  db:
    bizDB:
      dbType: sqlite
      dsn: "<your conf>"
      mark: "<your conf>"
    extraDB:
      dbType: sqlite
      dsn: "<your conf>"
      mark: "<your conf>"
oauth2Conf:
  github:
    endPoint: github
    clientId: "<your conf>"
    clientSecret: "<your conf>"
    redirectUrl: "<your conf>"
    scopes: ["<your conf>"]
  google:
    endPoint: google
    clientId: "<your conf>"
    clientSecret: "<your conf>"
    redirectUrl: "<your conf>"
    scopes: ["<your conf>"]
jwtConf:
  salt: "<your conf>"
  expired: "15d"
